<%@ Page Title="Game builder" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="GameBuilder.aspx.cs" Inherits="LearningSystem.Teacher.GameBuilder" %>
<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
<h1>Game builder</h1><asp:Label ID="lblLock" runat="server" Visible="false" Text="Attempts exist: game content, template and structural order are locked. Title, description and publication remain editable." />
<section class="form-card"><h2>Game settings</h2><asp:ValidationSummary ID="vsSettings" runat="server" ValidationGroup="Settings" />
<div class="field"><asp:Label ID="lblTitle" runat="server" AssociatedControlID="txtTitle" Text="Title" /><asp:TextBox ID="txtTitle" runat="server" MaxLength="100" /><asp:RequiredFieldValidator ID="rfvTitle" runat="server" ControlToValidate="txtTitle" ValidationGroup="Settings" ErrorMessage="Enter a title." /><asp:RegularExpressionValidator ID="revTitle" runat="server" ControlToValidate="txtTitle" ValidationGroup="Settings" ValidationExpression="^[\s\S]{3,100}$" ErrorMessage="Title must be 3–100 characters." /></div>
<div class="field"><asp:Label ID="lblDescription" runat="server" AssociatedControlID="txtDescription" Text="Description (optional)" /><asp:TextBox ID="txtDescription" runat="server" TextMode="MultiLine" MaxLength="1000" /><asp:RegularExpressionValidator ID="revDescription" runat="server" ControlToValidate="txtDescription" ValidationGroup="Settings" ValidationExpression="^[\s\S]{0,1000}$" ErrorMessage="Description must be at most 1000 characters." /></div>
<div class="field"><asp:Label ID="lblTemplate" runat="server" AssociatedControlID="ddlTemplate" Text="Game template" /><asp:DropDownList ID="ddlTemplate" runat="server"><asp:ListItem>Matching</asp:ListItem><asp:ListItem>Memory</asp:ListItem><asp:ListItem>Scramble</asp:ListItem><asp:ListItem>Sort</asp:ListItem></asp:DropDownList></div>
<div class="field"><asp:Label ID="lblOrder" runat="server" AssociatedControlID="txtOrder" Text="Activity order" /><asp:TextBox ID="txtOrder" runat="server" TextMode="Number" /><asp:RequiredFieldValidator ID="rfvOrder" runat="server" ControlToValidate="txtOrder" ValidationGroup="Settings" ErrorMessage="Enter an order." /><asp:RangeValidator ID="rvOrder" runat="server" ControlToValidate="txtOrder" ValidationGroup="Settings" Type="Integer" MinimumValue="1" MaximumValue="2147483647" ErrorMessage="Order must be a positive integer." /></div>
<div class="field"><asp:Label ID="lblStatus" runat="server" AssociatedControlID="ddlStatus" Text="Publication" /><asp:DropDownList ID="ddlStatus" runat="server"><asp:ListItem>Draft</asp:ListItem><asp:ListItem>Published</asp:ListItem></asp:DropDownList></div>
<p>Save as Draft, add content, then publish. The template locks once items exist. Remove empty Sort groups before changing the template.</p>
<div class="actions"><asp:Button ID="btnSave" runat="server" Text="Save settings" ValidationGroup="Settings" OnClick="SaveSettings" /><asp:Button ID="btnCancel" runat="server" Text="Cancel" CausesValidation="false" OnClick="Cancel" /><asp:HyperLink ID="lnkPreview" runat="server" Text="Preview" /><asp:Button ID="btnDelete" runat="server" Text="Delete game" ValidationGroup="Action" OnClick="DeleteGame" OnClientClick="return confirm('Delete this game and its content? Attempts block deletion.');" /></div></section>
<asp:Panel ID="pnlGroups" runat="server"><h2>Sort groups</h2><p>Publish with 2–4 groups and at least 2 items per group. A group containing items cannot be deleted.</p>
<div class="table-scroll" role="region" aria-label="Sort groups" tabindex="0"><asp:GridView ID="gvGroups" runat="server" AutoGenerateColumns="false" Caption="Sort groups" UseAccessibleHeader="true" EmptyDataText="No groups yet." OnRowCommand="GroupCommand"><Columns><asp:BoundField DataField="GroupName" HeaderText="Group" HtmlEncode="true" /><asp:TemplateField HeaderText="Actions"><ItemTemplate><asp:Button ID="btnEditGroup" runat="server" Text="Edit" CommandName="EditGroup" CommandArgument='<%# Eval("GroupID") %>' ValidationGroup="Action" /><asp:Button ID="btnDeleteGroup" runat="server" Text="Delete" CommandName="DeleteGroup" CommandArgument='<%# Eval("GroupID") %>' ValidationGroup="Action" OnClientClick="return confirm('Delete this empty group?');" /></ItemTemplate></asp:TemplateField></Columns></asp:GridView></div>
<asp:Panel ID="pnlGroupForm" runat="server" CssClass="form-card"><h3>Add / edit group</h3><asp:ValidationSummary ID="vsGroup" runat="server" ValidationGroup="Group" /><asp:Label ID="lblGroupName" runat="server" AssociatedControlID="txtGroupName" Text="Group name" /><asp:TextBox ID="txtGroupName" runat="server" MaxLength="50" /><asp:RequiredFieldValidator ID="rfvGroup" runat="server" ControlToValidate="txtGroupName" ValidationGroup="Group" ErrorMessage="Enter a group name." /><asp:RegularExpressionValidator ID="revGroup" runat="server" ControlToValidate="txtGroupName" ValidationGroup="Group" ValidationExpression="^[\s\S]{1,50}$" ErrorMessage="Group name must be 1–50 characters." /><div class="actions"><asp:Button ID="btnSaveGroup" runat="server" Text="Save group" ValidationGroup="Group" OnClick="SaveGroup" /><asp:Button ID="btnCancelGroup" runat="server" Text="Cancel group edit" CausesValidation="false" OnClick="CancelEdit" /></div></asp:Panel></asp:Panel>
<asp:Panel ID="pnlItems" runat="server"><h2>Game content</h2><p>Matching: at least 4 pairs. Memory: 4–12 pairs. Word Scramble: at least 3 words with hints. Sort: at least 2 items in each group.</p>
<div class="table-scroll" role="region" aria-label="Game items" tabindex="0"><asp:GridView ID="gvItems" runat="server" AutoGenerateColumns="false" Caption="Game items" UseAccessibleHeader="true" EmptyDataText="No game items yet." OnRowCommand="ItemCommand"><Columns><asp:BoundField DataField="ItemText" HeaderText="Item / word" HtmlEncode="true" /><asp:BoundField DataField="MatchText" HeaderText="Match / hint" HtmlEncode="true" /><asp:BoundField DataField="GroupName" HeaderText="Group" HtmlEncode="true" /><asp:TemplateField HeaderText="Actions"><ItemTemplate><asp:Button ID="btnEditItem" runat="server" Text="Edit" CommandName="EditItem" CommandArgument='<%# Eval("ItemID") %>' ValidationGroup="Action" /><asp:Button ID="btnDeleteItem" runat="server" Text="Delete" CommandName="DeleteItem" CommandArgument='<%# Eval("ItemID") %>' ValidationGroup="Action" OnClientClick="return confirm('Delete this game item?');" /></ItemTemplate></asp:TemplateField></Columns></asp:GridView></div>
<asp:Panel ID="pnlItemForm" runat="server" CssClass="form-card"><h3>Add / edit item</h3><asp:ValidationSummary ID="vsItem" runat="server" ValidationGroup="Item" /><asp:CustomValidator ID="cvItem" runat="server" ValidationGroup="Item" OnServerValidate="ValidateItem" ErrorMessage="Check the item, match/hint and group. Scramble words need 3–15 letters; other item text 1–100 characters; match/hint 1–200 characters." />
<div class="field"><asp:Label ID="lblItem" runat="server" AssociatedControlID="txtItem" Text="Item text" /><asp:TextBox ID="txtItem" runat="server" MaxLength="100" /><asp:RequiredFieldValidator ID="rfvItem" runat="server" ControlToValidate="txtItem" ValidationGroup="Item" ErrorMessage="Enter item text." /></div>
<asp:Panel ID="pnlMatch" runat="server" CssClass="field"><asp:Label ID="lblMatch" runat="server" AssociatedControlID="txtMatch" Text="Match / hint" /><asp:TextBox ID="txtMatch" runat="server" MaxLength="200" /><asp:RequiredFieldValidator ID="rfvMatch" runat="server" ControlToValidate="txtMatch" ValidationGroup="Item" ErrorMessage="Enter match text or a hint." /></asp:Panel>
<asp:Panel ID="pnlGroupChoice" runat="server" CssClass="field"><asp:Label ID="lblGroupChoice" runat="server" AssociatedControlID="ddlGroup" Text="Correct group" /><asp:DropDownList ID="ddlGroup" runat="server" /><asp:RequiredFieldValidator ID="rfvGroupChoice" runat="server" ControlToValidate="ddlGroup" ValidationGroup="Item" ErrorMessage="Choose a group." /></asp:Panel>
<div class="actions"><asp:Button ID="btnSaveItem" runat="server" Text="Save item" ValidationGroup="Item" OnClick="SaveItem" /><asp:Button ID="btnCancelItem" runat="server" Text="Cancel item edit" CausesValidation="false" OnClick="CancelEdit" /></div></asp:Panel></asp:Panel>
<asp:Panel ID="pnlResults" runat="server"><h2>Learner attempts</h2><div class="table-scroll" role="region" aria-label="Attempts on this owned game" tabindex="0"><asp:GridView ID="gvResults" runat="server" AutoGenerateColumns="false" Caption="Attempts on this owned game" UseAccessibleHeader="true" EmptyDataText="No learner attempts yet."><Columns><asp:BoundField DataField="FullName" HeaderText="Learner" HtmlEncode="true" /><asp:BoundField DataField="SubmittedAt" HeaderText="Submitted (UTC)" DataFormatString="{0:yyyy-MM-dd HH:mm:ss}" /><asp:BoundField DataField="ScorePercent" HeaderText="Score (%)" DataFormatString="{0:F2}" /><asp:BoundField DataField="TimeTakenSeconds" HeaderText="Time (seconds)" /></Columns></asp:GridView></div></asp:Panel>
</asp:Content>

