<%@ Page Title="Scenario builder" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="ScenarioBuilder.aspx.cs" Inherits="LearningSystem.Teacher.ScenarioBuilder" %>
<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
<h1>Scenario builder</h1>
<asp:Label ID="lblLock" runat="server" Visible="false" Text="Attempts exist: steps, choices, start step and structural order are locked. Title, description and publication remain editable." />
<section class="form-card"><h2>Scenario settings</h2>
<asp:ValidationSummary ID="vsSettings" runat="server" ValidationGroup="Settings" />
<div class="field"><asp:Label ID="lblTitle" runat="server" AssociatedControlID="txtTitle" Text="Title (3–100 characters)" /><asp:TextBox ID="txtTitle" runat="server" MaxLength="100" /><asp:RequiredFieldValidator ID="rfvTitle" runat="server" ControlToValidate="txtTitle" ValidationGroup="Settings" ErrorMessage="Enter a title." /><asp:RegularExpressionValidator ID="revTitle" runat="server" ControlToValidate="txtTitle" ValidationGroup="Settings" ValidationExpression="^[\s\S]{3,100}$" ErrorMessage="Title must contain 3–100 characters." /></div>
<div class="field"><asp:Label ID="lblDescription" runat="server" AssociatedControlID="txtDescription" Text="Introduction (10–1000 characters)" /><asp:TextBox ID="txtDescription" runat="server" TextMode="MultiLine" MaxLength="1000" /><asp:RequiredFieldValidator ID="rfvDescription" runat="server" ControlToValidate="txtDescription" ValidationGroup="Settings" ErrorMessage="Enter an introduction." /><asp:RegularExpressionValidator ID="revDescription" runat="server" ControlToValidate="txtDescription" ValidationGroup="Settings" ValidationExpression="^[\s\S]{10,1000}$" ErrorMessage="Introduction must contain 10–1000 characters." /></div>
<div class="field"><asp:Label ID="lblOrder" runat="server" AssociatedControlID="txtOrder" Text="Activity order" /><asp:TextBox ID="txtOrder" runat="server" TextMode="Number" /><asp:RequiredFieldValidator ID="rfvOrder" runat="server" ControlToValidate="txtOrder" ValidationGroup="Settings" ErrorMessage="Enter an order." /><asp:RangeValidator ID="rvOrder" runat="server" ControlToValidate="txtOrder" ValidationGroup="Settings" Type="Integer" MinimumValue="1" MaximumValue="2147483647" ErrorMessage="Order must be a positive integer." /></div>
<div class="field"><asp:Label ID="lblStatus" runat="server" AssociatedControlID="ddlStatus" Text="Publication" /><asp:DropDownList ID="ddlStatus" runat="server"><asp:ListItem>Draft</asp:ListItem><asp:ListItem>Published</asp:ListItem></asp:DropDownList></div>
<p>Save a Draft first, add steps and choices, choose a start step, then Check &amp; Publish. Loops are allowed. Every non-ending needs a choice; endings need outcome and feedback with no outgoing choices.</p>
<div class="actions"><asp:Button ID="btnSave" runat="server" Text="Save settings" ValidationGroup="Settings" OnClick="SaveSettings" /><asp:Button ID="btnPublish" runat="server" Text="Check &amp; Publish" ValidationGroup="Settings" OnClick="Publish" /><asp:Button ID="btnCancel" runat="server" Text="Cancel" CausesValidation="false" OnClick="Cancel" /><asp:HyperLink ID="lnkPreview" runat="server" Text="Preview" /><asp:Button ID="btnDelete" runat="server" Text="Delete scenario" ValidationGroup="Action" OnClick="DeleteScenario" OnClientClick="return confirm('Delete this scenario and its content? Attempts block deletion.');" /></div>
</section>
<asp:Panel ID="pnlContent" runat="server">
<h2>Start step</h2><p>Current start: <asp:Literal ID="litStart" runat="server" Mode="Encode" /></p>
<asp:Panel ID="pnlStartForm" runat="server" CssClass="form-card"><asp:ValidationSummary ID="vsStart" runat="server" ValidationGroup="Start" /><asp:Label ID="lblStart" runat="server" AssociatedControlID="ddlStart" Text="Choose start step" /><asp:DropDownList ID="ddlStart" runat="server" /><asp:RequiredFieldValidator ID="rfvStart" runat="server" ControlToValidate="ddlStart" ValidationGroup="Start" ErrorMessage="Choose a start step." /><div class="actions"><asp:Button ID="btnStart" runat="server" Text="Set start step" ValidationGroup="Start" OnClick="SaveStart" /><asp:Button ID="btnCancelStart" runat="server" Text="Cancel" CausesValidation="false" OnClick="CancelEdit" /></div></asp:Panel>
<h2>Steps</h2>
<div class="table-scroll" role="region" aria-label="Scenario steps (StepID order)" tabindex="0"><asp:GridView ID="gvSteps" runat="server" AutoGenerateColumns="false" Caption="Scenario steps (StepID order)" UseAccessibleHeader="true" EmptyDataText="No steps yet." OnRowCommand="StepCommand"><Columns>
<asp:BoundField DataField="StepID" HeaderText="Step ID" /><asp:BoundField DataField="StepText" HeaderText="Step text" HtmlEncode="true" /><asp:CheckBoxField DataField="IsEnding" HeaderText="Ending" /><asp:BoundField DataField="Outcome" HeaderText="Outcome" HtmlEncode="true" />
<asp:TemplateField HeaderText="Actions"><ItemTemplate><asp:Button ID="btnEditStep" runat="server" Text="Edit" CommandName="EditStep" CommandArgument='<%# Eval("StepID") %>' ValidationGroup="Action" /><asp:Button ID="btnDeleteStep" runat="server" Text="Delete" CommandName="DeleteStep" CommandArgument='<%# Eval("StepID") %>' ValidationGroup="Action" OnClientClick="return confirm('Delete this step and its outgoing choices? Start steps, incoming references and attempts block deletion.');" /></ItemTemplate></asp:TemplateField></Columns></asp:GridView></div>
<asp:Panel ID="pnlStepForm" runat="server" CssClass="form-card"><h3>Add / edit step <asp:Literal ID="litEditingStep" runat="server" Mode="Encode" /></h3>
<asp:ValidationSummary ID="vsStep" runat="server" ValidationGroup="Step" /><asp:CustomValidator ID="cvStep" runat="server" ValidationGroup="Step" OnServerValidate="ValidateStep" ErrorMessage="Check ending outcome/feedback, image type/size and alt text." />
<div class="field"><asp:Label ID="lblStep" runat="server" AssociatedControlID="txtStep" Text="Step text (10–1000 characters)" /><asp:TextBox ID="txtStep" runat="server" TextMode="MultiLine" MaxLength="1000" /><asp:RequiredFieldValidator ID="rfvStep" runat="server" ControlToValidate="txtStep" ValidationGroup="Step" ErrorMessage="Enter step text." /><asp:RegularExpressionValidator ID="revStep" runat="server" ControlToValidate="txtStep" ValidationGroup="Step" ValidationExpression="^[\s\S]{10,1000}$" ErrorMessage="Step text must contain 10–1000 characters." /></div>
<div class="field"><asp:Label ID="lblImage" runat="server" AssociatedControlID="fuImage" Text="Optional image (JPG, PNG, GIF; up to 2 MB)" /><asp:FileUpload ID="fuImage" runat="server" /><asp:CheckBox ID="chkRemoveImage" runat="server" Text="Remove existing image (a new upload replaces it)" /><asp:Literal ID="litImage" runat="server" EnableViewState="false" /></div>
<div class="field"><asp:Label ID="lblAlt" runat="server" AssociatedControlID="txtAlt" Text="Image alt text (5–150 characters when an image exists)" /><asp:TextBox ID="txtAlt" runat="server" MaxLength="150" /></div>
<div class="field"><asp:CheckBox ID="chkEnding" runat="server" Text="This is an ending step" /></div>
<div class="field"><asp:Label ID="lblOutcome" runat="server" AssociatedControlID="ddlOutcome" Text="Ending outcome" /><asp:DropDownList ID="ddlOutcome" runat="server"><asp:ListItem Value="">Choose outcome</asp:ListItem><asp:ListItem>Best</asp:ListItem><asp:ListItem>Acceptable</asp:ListItem><asp:ListItem>Poor</asp:ListItem></asp:DropDownList></div>
<div class="field"><asp:Label ID="lblFeedback" runat="server" AssociatedControlID="txtFeedback" Text="Ending feedback (10–500 characters)" /><asp:TextBox ID="txtFeedback" runat="server" TextMode="MultiLine" MaxLength="500" /></div>
<p>Delete outgoing choices before making a step an ending. Saving as a non-ending clears outcome and feedback.</p>
<div class="actions"><asp:Button ID="btnSaveStep" runat="server" Text="Save step" ValidationGroup="Step" OnClick="SaveStep" /><asp:Button ID="btnCancelStep" runat="server" Text="Cancel step edit" CausesValidation="false" OnClick="CancelEdit" /></div></asp:Panel>
<h2>Choices</h2>
<div class="table-scroll" role="region" aria-label="Scenario choices (ChoiceID order)" tabindex="0"><asp:GridView ID="gvChoices" runat="server" AutoGenerateColumns="false" Caption="Scenario choices (ChoiceID order)" UseAccessibleHeader="true" EmptyDataText="No choices yet." OnRowCommand="ChoiceCommand"><Columns><asp:BoundField DataField="FromStepID" HeaderText="From step" /><asp:BoundField DataField="ChoiceText" HeaderText="Choice" HtmlEncode="true" /><asp:BoundField DataField="NextStepID" HeaderText="Next step" /><asp:TemplateField HeaderText="Actions"><ItemTemplate><asp:Button ID="btnEditChoice" runat="server" Text="Edit" CommandName="EditChoice" CommandArgument='<%# Eval("ChoiceID") %>' ValidationGroup="Action" /><asp:Button ID="btnDeleteChoice" runat="server" Text="Delete" CommandName="DeleteChoice" CommandArgument='<%# Eval("ChoiceID") %>' ValidationGroup="Action" OnClientClick="return confirm('Delete this choice?');" /></ItemTemplate></asp:TemplateField></Columns></asp:GridView></div>
<asp:Panel ID="pnlChoiceForm" runat="server" CssClass="form-card"><h3>Add / edit choice <asp:Literal ID="litEditingChoice" runat="server" Mode="Encode" /></h3><asp:ValidationSummary ID="vsChoice" runat="server" ValidationGroup="Choice" />
<div class="field"><asp:Label ID="lblFrom" runat="server" AssociatedControlID="ddlFrom" Text="From step (non-ending)" /><asp:DropDownList ID="ddlFrom" runat="server" /><asp:RequiredFieldValidator ID="rfvFrom" runat="server" ControlToValidate="ddlFrom" ValidationGroup="Choice" ErrorMessage="Choose a source step." /></div>
<div class="field"><asp:Label ID="lblNext" runat="server" AssociatedControlID="ddlNext" Text="Next step (different step in this scenario)" /><asp:DropDownList ID="ddlNext" runat="server" /><asp:RequiredFieldValidator ID="rfvNext" runat="server" ControlToValidate="ddlNext" ValidationGroup="Choice" ErrorMessage="Choose a destination step." /></div>
<div class="field"><asp:Label ID="lblChoice" runat="server" AssociatedControlID="txtChoice" Text="Choice text (2–150 characters)" /><asp:TextBox ID="txtChoice" runat="server" MaxLength="150" /><asp:RequiredFieldValidator ID="rfvChoice" runat="server" ControlToValidate="txtChoice" ValidationGroup="Choice" ErrorMessage="Enter choice text." /><asp:RegularExpressionValidator ID="revChoice" runat="server" ControlToValidate="txtChoice" ValidationGroup="Choice" ValidationExpression="^[\s\S]{2,150}$" ErrorMessage="Choice text must contain 2–150 characters." /></div>
<div class="actions"><asp:Button ID="btnSaveChoice" runat="server" Text="Save choice" ValidationGroup="Choice" OnClick="SaveChoice" /><asp:Button ID="btnCancelChoice" runat="server" Text="Cancel choice edit" CausesValidation="false" OnClick="CancelEdit" /></div></asp:Panel>
<h2>Outcome summary</h2><p>Counts include saved learner attempts only, grouped by ending step and outcome.</p>
<div class="table-scroll" role="region" aria-label="Attempts by ending step and outcome in this owned scenario" tabindex="0"><asp:GridView ID="gvSummary" runat="server" AutoGenerateColumns="false" Caption="Attempts by ending step and outcome in this owned scenario" UseAccessibleHeader="true" EmptyDataText="No saved learner attempts yet."><Columns><asp:BoundField DataField="StepID" HeaderText="Ending step" /><asp:BoundField DataField="StepText" HeaderText="Ending text" HtmlEncode="true" /><asp:BoundField DataField="Outcome" HeaderText="Outcome" HtmlEncode="true" /><asp:BoundField DataField="Attempts" HeaderText="Attempts" /></Columns></asp:GridView></div>
</asp:Panel>
</asp:Content>

