<%@ Page Title="Course details" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="CourseDetails.aspx.cs" Inherits="LearningSystem.CourseDetails" %>
<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
<section class="course-heading" aria-label="Course introduction"><h1><asp:Literal ID="litTitle" runat="server" Mode="Encode" /></h1>
<asp:Image ID="imgCover" runat="server" CssClass="course-cover" Visible="false" />
<p><asp:Literal ID="litDescription" runat="server" Mode="Encode" /></p><p class="metadata"><asp:Literal ID="litMetadata" runat="server" Mode="Encode" /></p>
<div class="actions"><asp:Button ID="btnEnrol" runat="server" Text="Enrol for free" OnClick="Enrol" ValidationGroup="Enrol" Visible="false" /><asp:HyperLink ID="lnkLogin" runat="server" Text="Log in to enrol" Visible="false" /><asp:HyperLink ID="lnkStudy" runat="server" Text="Open course" Visible="false" /><a href="Courses.aspx">Back to courses</a></div>
</section><asp:PlaceHolder ID="phOutline" runat="server" />
<section id="reviews"><h2>Course reviews</h2><p><asp:Literal ID="litRating" runat="server" Mode="Encode" /></p><asp:Label ID="lblNoReviews" runat="server" Text="No reviews yet." />
<asp:Repeater ID="rptReviews" runat="server"><ItemTemplate><article class="form-card"><h3><%#: Eval("FullName") %> · <%#: Eval("Rating") %> / 5</h3><p class="preserve-lines"><%#: Eval("Comment") %></p><p>Posted <%#: Eval("PostedDate","{0:yyyy-MM-dd}") %> UTC</p></article></ItemTemplate></asp:Repeater>
<asp:Panel ID="pnlReview" runat="server" Visible="false" CssClass="form-card"><h3>Your review</h3><asp:ValidationSummary ID="vsReview" runat="server" ValidationGroup="Review" />
<div class="field"><asp:Label ID="lblRating" runat="server" AssociatedControlID="txtRating" Text="Rating (1–5)" /><asp:TextBox ID="txtRating" runat="server" TextMode="Number" /><asp:RequiredFieldValidator ID="rfvRating" runat="server" ControlToValidate="txtRating" ValidationGroup="Review" ErrorMessage="Enter a rating." /><asp:RangeValidator ID="rvRating" runat="server" ControlToValidate="txtRating" Type="Integer" MinimumValue="1" MaximumValue="5" ValidationGroup="Review" ErrorMessage="Rating must be an integer 1–5." /></div>
<div class="field"><asp:Label ID="lblComment" runat="server" AssociatedControlID="txtComment" Text="Comment (10–1000 characters)" /><asp:TextBox ID="txtComment" runat="server" TextMode="MultiLine" Rows="5" /><asp:RequiredFieldValidator ID="rfvComment" runat="server" ControlToValidate="txtComment" ValidationGroup="Review" ErrorMessage="Enter a comment." /><asp:RegularExpressionValidator ID="revComment" runat="server" ControlToValidate="txtComment" ValidationExpression="^[\s\S]{10,1000}$" ValidationGroup="Review" ErrorMessage="Comment must be 10–1000 characters." /></div>
<div class="actions"><asp:Button ID="btnReview" runat="server" Text="Save review" ValidationGroup="Review" OnClick="SaveReview" /><asp:Button ID="btnDeleteReview" runat="server" Text="Delete my review" Visible="false" ValidationGroup="RemoveReview" OnClick="DeleteReview" OnClientClick="return confirm('Delete your review?');" /><asp:HyperLink ID="lnkCancelReview" runat="server" Text="Cancel" CssClass="button secondary" /></div></asp:Panel></section>
</asp:Content>

