<%@ Page Title="Help" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Help.aspx.cs" Inherits="LearningSystem.Help" %>
<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
<h1>Help</h1><p>Find answers for visitors, learners and teachers.</p>
<section><h2>Getting started</h2><details><summary>Can I look at courses without an account?</summary><p>Yes. Browse published courses and open materials labelled free preview. Register or log in as a learner to enrol and study the other lessons.</p></details><details><summary>Where do I find courses?</summary><p>Use <a href="Courses.aspx">Courses</a> to search titles and descriptions or choose a subject.</p></details></section>
<section><h2>For learners</h2><details><summary>How do I enrol?</summary><p>Log in, open a published course and choose Enrol for free. Your course then appears in My courses.</p></details><details><summary>How does progress work?</summary><p>Mark materials complete after studying them. Published activities count when you submit an attempt; a discussion counts when you have a surviving post or reply. Each published item counts once. Progress is recalculated when content changes.</p></details><details><summary>What happens if I leave?</summary><p>Leaving removes enrolment, but retains your learning records. Re-enrol to regain access and continue with your previous progress.</p></details><details><summary>Why is my course unavailable?</summary><p>The teacher has unpublished it. It stays in My courses as Currently unavailable, and your saved learning records remain.</p></details></section>
<section><h2>For teachers</h2><details><summary>How do I become a teacher?</summary><p>Apply through Register and wait for administrator approval. Approved teachers can create and manage their own courses.</p></details><details><summary>Does preview affect learner records?</summary><p>No. Teacher and administrator material previews are read-only, including drafts. The preview banner and Exit preview link identify this mode.</p></details></section>
<section><h2>Frequently asked questions</h2><asp:Literal ID="litFAQ" runat="server" /></section>
<section><h2>Keyboard shortcuts</h2><ul><li>Alt+H: Home</li><li>Alt+C: Courses catalogue</li><li>Alt+D: your role dashboard (no action for visitors)</li><li>Alt+Q: Help / FAQ</li></ul><p>Shortcuts do nothing while typing in inputs, textareas, selects or editable content, during composition, on repeated keys or with Ctrl, Meta or Shift. Some browsers or operating systems reserve these combinations; use the navigation links when a shortcut is unavailable.</p></section>
</asp:Content>
