<%@ Page Title="My results" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="MyResults.aspx.cs" Inherits="LearningSystem.Learner.MyResults" %>
<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server"><h1>My results</h1>
<section class="form-card"><h2>Filter results</h2><asp:ValidationSummary ID="vsFilters" runat="server" ValidationGroup="Filter" />
<div class="field"><asp:Label ID="lblCourse" runat="server" AssociatedControlID="ddlCourse" Text="Course" /><asp:DropDownList ID="ddlCourse" runat="server" AutoPostBack="true" OnSelectedIndexChanged="CourseChanged" /></div>
<div class="field"><asp:Label ID="lblActivity" runat="server" AssociatedControlID="ddlActivity" Text="Activity" /><asp:DropDownList ID="ddlActivity" runat="server" /></div>
<div class="actions"><asp:Button ID="btnFilter" runat="server" Text="Apply filters" ValidationGroup="Filter" OnClick="ApplyFilters" /><asp:Button ID="btnCancel" runat="server" Text="Cancel / clear filters" CausesValidation="false" OnClick="ClearFilters" /><a href="Dashboard.aspx">Dashboard</a></div></section>
<h2>Submitted attempts</h2>
<div class="table-scroll" role="region" aria-label="Submitted attempts, newest first (UTC)" tabindex="0"><asp:GridView ID="gvResults" runat="server" AutoGenerateColumns="false" Caption="Submitted attempts, newest first (UTC)" UseAccessibleHeader="true" EmptyDataText="No submitted attempts match these filters." AllowPaging="true" PageSize="10" OnPageIndexChanging="ChangePage"><Columns>
<asp:BoundField DataField="CourseTitle" HeaderText="Course" HtmlEncode="true" /><asp:BoundField DataField="Title" HeaderText="Activity" HtmlEncode="true" /><asp:BoundField DataField="ActivityType" HeaderText="Type" />

<asp:BoundField DataField="SubmittedAt" HeaderText="Submitted (UTC)" DataFormatString="{0:yyyy-MM-dd HH:mm:ss}" /><asp:BoundField DataField="Summary" HeaderText="Result" HtmlEncode="true" />
<asp:TemplateField HeaderText="Review"><ItemTemplate><asp:HyperLink ID="lnkReview" runat="server" Text="Review course" NavigateUrl='<%# "~/CourseDetails.aspx?id="+Eval("CourseID")+"#reviews" %>' Visible='<%# (bool)Eval("Enrolled") && (string)Eval("CourseStatus")=="Published" %>' /></ItemTemplate></asp:TemplateField><asp:TemplateField HeaderText="Details"><ItemTemplate><asp:HyperLink ID="lnkResult" runat="server" Text='<%# Eval("LinkText") %>' NavigateUrl='<%# Eval("ResultUrl") %>' Visible='<%# !String.IsNullOrEmpty((string)Eval("ResultUrl")) %>' /></ItemTemplate></asp:TemplateField>
</Columns></asp:GridView></div>
<h2>Quiz and game scores</h2><p>Each row summarises one learner's saved attempts on one activity. Confidence and scenario outcomes are not percentage scores.</p>
<div class="table-scroll" role="region" aria-label="Quiz and game attempt counts, best, latest and average scores" tabindex="0"><asp:GridView ID="gvScores" runat="server" AutoGenerateColumns="false" Caption="Quiz and game attempt counts, best, latest and average scores" UseAccessibleHeader="true" EmptyDataText="No quiz or game scores match these filters."><Columns><asp:BoundField DataField="CourseTitle" HeaderText="Course" HtmlEncode="true" /><asp:BoundField DataField="Title" HeaderText="Activity" HtmlEncode="true" /><asp:BoundField DataField="Attempts" HeaderText="Attempts" /><asp:BoundField DataField="BestScore" HeaderText="Best (%)" DataFormatString="{0:F2}" /><asp:BoundField DataField="LatestScore" HeaderText="Latest (%)" DataFormatString="{0:F2}" /><asp:BoundField DataField="AverageScore" HeaderText="Average (%)" DataFormatString="{0:F2}" /></Columns></asp:GridView></div><p>Your saved history remains here if you leave a course or it becomes unavailable. Detailed content links appear only when you have access.</p></asp:Content>

